### PR TITLE
Added debug menu support for FW 9.03

### PR DESCRIPTION
**Pull request by Simopich**
Tested and working on my 9.03 PS4 Pro.

### CODE REVIEW

**Comment by KarimosDz** [comment]
I have a 9.03 device and I'm going to try it now

**Comment by Simopich** [comment]
> I have a 9.03 device and I'm going to try it now

Nice, thanks!

**Comment by Simopich** [comment]
I've just added a patch that fixes the debug settings errors

**Comment by KarimosDz** [comment]
debug menu worked for me
Thanks @Simopich

**Comment by Simopich** [comment]
> debug menu worked for me
> Thanks @Simopich 

Np!

**Comment by RotaryGabry** [comment]
Also worked for me! (PS4 Pro 9.03)

**Pull request merged**
